### ISSUE TITLE
`promiseStateAsync` handles errors (observer effect)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/p-state#2]
Rejected promises show up as uncaught errors in the console and cause Node 15 to exit with 1.

`pState` however handles these errors and they're no longer reported by either platform.

Example:

```js
async function hi () {throw new Error()}
const p = hi();
// => undefined

 VM366:1 Uncaught (in promise) Error
    at hi (<anonymous>:1:29)
    at <anonymous>:2:11
```
```js
async function hi () {throw new Error()}
const p2 = hi();
promiseStateAsync(p2);
// => Promise {<fulfilled>: "rejected"}
```

Chrome:

<img width="310" alt="" src="https://user-images.githubusercontent.com/1402241/100055992-74329000-2dea-11eb-88bf-50526d156a81.png">

**Comment by fregante** [comment]
Strangely enough, your test include an explicit `catch` to catch the unhandled error:

https://github.com/sindresorhus/p-state/blob/5ea9b33185106c3ac6016901501d87f97dae6237/test.js#L36

But if I run the same code in the Node repl:

`UnhandledPromiseRejectionWarning` only without `p-state` in Node 14:

<img width="493" alt="" src="https://user-images.githubusercontent.com/1402241/100057433-0b98e280-2ded-11eb-9071-95b88b914a2a.png">


`ERR_UNHANDLED_REJECTION` with exit code 1 only without `p-state` in Node 15:

<img width="494" alt="" src="https://user-images.githubusercontent.com/1402241/100057381-e906c980-2dec-11eb-80f3-af9996785a73.png">

**Comment by sindresorhus** [comment]
We could add the following above the try/catch to make it work as expected:

```js
await new Promise(resolve => {
	if (typeof setImmediate === 'function') {
		setImmediate(resolve);
	} else {
		setTimeout(resolve);
	}
});
```

The downside is that the state will take an event loop run to be returned...

I'm open to other ideas.

If we cannot come up with a better solution, we could make the above opt-in.

**Comment by fregante** [comment]
I was going to suggest `Promise.allSettled` but didn't realize that it had the same problem.

Even `finally` hides the error:

```js

	const marker = Symbol('marker');
    let return_;
	try {
		return_ = await Promise.race([promise, marker]) === marker ? 'pending' : 'fulfilled';
	} catch (e){
		return_ = 'rejected';
        throw e; // Re-throw
	} finally {
        return return_
    }
```

**Comment by fregante** [comment]
> we could make the above opt-in.

Swallowing errors doesn't seem worth saving a few milliseconds; I'd make the opposite opt-in.

**Comment by CloudNStoyan** [comment]
Sorry to comment on an old issue, but I was wondering what was the reason that the error was swallowed and why skipping one event loop run fixes it.

I assume this part of the code just makes sure the try-catch is called on the next event loop run but how does this fix the issue?

```js
await new Promise(resolve => {
	if (typeof setImmediate === 'function') {
		setImmediate(resolve);
	} else {
		setTimeout(resolve);
	}
});
```

**Comment by fregante** [comment]
An "unhandled rejection" is a rejection that isn't "immediately" handled (e.g. `.catch()` is called on it). The runtime will _throw_ the error due to an unhandled rejection and only then you can call `.catch()` without affecting this behavior.

**Comment by CloudNStoyan** [comment]
Thanks for the response!

I was curious and did some testing with the code and I think I have found a bug.

Using this snippet of code:
```js
window.addEventListener("unhandledrejection", (ev) => {
  console.warn(`UNHANDLED PROMISE REJECTION: ${ev.reason}`);
});
window.addEventListener('error', (ev) => {
  console.warn(`UNHANDLED ERROR: ${ev.reason}`);
});

await (async () => {
  const promise = Promise.reject("dinosaur");

  await new Promise((resolve) => {
    // here
    setTimeout(resolve);
  });

  const marker = {};

  try {
    return (await Promise.race([promise, marker])) === marker
      ? "pending"
      : "fulfilled";
  } catch {
    return "rejected";
  }
})();
```

Using this snippet in the Dev Console in a browser will not trigger the `unhandledrejection` event.
This seems to happen because of the `setTimeout(resolve)`, by default when the `delay` arg is omitted its set to 0, and with this configuration the unhandled rejection is still swallowed by `Promise.race`. Changing the delay to `1` instead of `0` fixed it for me.

```js
  await new Promise((resolve) => {
    setTimeout(resolve, 1);
  });
```

Note: on Firefox you get a  `Uncaught (in promise) dinosaur` error in the Dev Tools but it doesn't trigger the `unhandledrejection` event.
![image](https://github.com/sindresorhus/p-state/assets/36141982/874c0210-101d-4f7e-8b19-3a847f0eaf19)

I have tested this behavior on the following platforms:
Win11 Chrome Version 122.0.6261.129
Win11 Firefox Version 123.0.1
macOS Sonoma 14.4 Chrome Version 122.0.6261.129
macOS Sonoma 14.4 Firefox Version 123.0.1
macOS Sonoma 14.4 Safari Version 17.4 (19618.1.15.11.12)

I tested it in node v18.16.1 and v20.11.0 and there it works with `setTimeout(resolve)` so its seems its only a browser bug.

**Comment by CloudNStoyan** [comment]
Also I have found that rejecting a promise after its been handled by `Promise.race` will swallow the error too

```js
window.addEventListener("unhandledrejection", (ev) => {
  console.warn(`UNHANDLED PROMISE REJECTION: ${ev.reason}`);
});

window.addEventListener('error', (ev) => {
  console.warn(`UNHANDLED ERROR: ${ev.reason}`);
});

const marker = Symbol("marker");

async function promiseStateAsync(promise) {
  if (!(typeof promise === "object" && typeof promise.then === "function")) {
    throw new TypeError(`Expected a promise, got ${typeof promise}`);
  }

  // Ensure unhandled rejections don't get swallowed.
  await new Promise((resolve) => {
    setTimeout(resolve);
  });

  try {
    return (await Promise.race([promise, marker])) === marker
      ? "pending"
      : "fulfilled";
  } catch {
    return "rejected";
  }
}

let reject;
let promise = new Promise((_res, rej) => {
  reject = rej;
});

const promiseState = await promiseStateAsync(promise);
console.log(promiseState);

setTimeout(() => {
  reject("dinosaur");
  console.log("the setTimeout triggered");
}, 1000);
```

Note: in Node I didn't use the event listeners
```js
window.addEventListener("unhandledrejection", (ev) => {
  console.warn(`UNHANDLED PROMISE REJECTION: ${ev.reason}`);
});

window.addEventListener('error', (ev) => {
  console.warn(`UNHANDLED ERROR: ${ev.reason}`);
});
```
Instead I was looking at the console if it will output an `UnhandledPromiseRejection` and exit with 1, which it didn't.

I have tested this behavior on the following platforms:
Win11 Chrome Version 122.0.6261.129
Win11 Firefox Version 123.0.1
macOS Sonoma 14.4 Chrome Version 122.0.6261.129
macOS Sonoma 14.4 Firefox Version 123.0.1
macOS Sonoma 14.4 Safari Version 17.4 (19618.1.15.11.12)
Node versions v18.16.1 and v20.11.0 on both Win11 and macOS Sonoma 14.4

Edit: this is not affected by the `setTimeout` bug, its a new one
Edit 2: this time even Firefox Dev Tools wont show you the error

**Comment by fregante** [comment]
It's possible that the browser handles this differently, yes. It's a runtime behavior we don't test outside Node. It's best to open dedicated bugs with your findings rather than commenting here.

**Comment by CloudNStoyan** [comment]
Thanks for your response!

I will create new bugs with my findings.
