### ISSUE TITLE
Return an object like allSettled

### ISSUE THREAD

**Issue by fregante** [sindresorhus/p-state#7]
I’m not sure if it’s worth the extra complexity:

```js
{
  state: 'pending',
  isFulfilled: false,
  isRejected: false,
  isPending: true,
}
``` 

```js
{
  state: 'rejected',
  isFulfilled: false,
  isRejected: true,
  isPending: false,
  reason: Error
}
```

**Comment by sindresorhus** [comment]
Do you have a specific need that this would solve?

**Comment by fregante** [comment]
The booleans make it more readable. The value/error can act as a sync variable if available. 

But actually in my case I can't use the sync method so it wouldn't work. It only work if the promise object itself "exploded" with these properties. 

```JavaScript 
const request = pExplode(fetch())
```

``` JavaScript 
// totally sync method
if (request.isFulfilled) 
  console.log("the promise already resolved with", request.value)
```

**Comment by sindresorhus** [comment]
Booleans are only tempting here because JS lack enums. This is something you would ideally model with an enum (not the sucky TS enum though). In a proper language like Swift, it would be something nice like:

```swift
if result == .fulfilled {}
```

And you wouldn't feel the need to litter a bunch a boolean properties onto the result.

**Comment by sindresorhus** [comment]
But back to the actual request; I don't think it's worth doing a breaking change for this.
