### ISSUE TITLE
Error calling the function `promiseStateSync`

### ISSUE THREAD

**Issue by vladyslav-kushnir** [sindresorhus/p-state#8]
`inspectedString.startsWith` is not a function.

Fix: 
```
const inspectedString = inspect(promise, {
		depth: 0,
		showProxy: false,
		maxStringLength: 0,
		breakLength: Number.POSITIVE_INFINITY,
	}).toString();   <<<--- .toString()
```

**Comment by papb** [comment]
Unable to reproduce, not even on Node.js v12. Also, [the Node.js documentation guarantees the return value of `inspect` to be a string](https://nodejs.org/docs/latest-v12.x/api/util.html#util_util_inspect_object_options). You must be mistaken.

**Comment by vladyslav-kushnir** [comment]
I have used https://www.npmjs.com/package/util. Probably it is a problem of the module itself and it doesn't follow the `inspect` specs. Thanks for looking into this tho.

**Comment by papb** [comment]
@vladyslav-kushnir You're welcome. I recommend you open an issue on that package about this. I'm surprised they aren't strictly following spec.
